import type { Config } from "tailwindcss";

// Mirrors the Tailwind config exported by Google Stitch (Kinetic Ghost design system).
// Keep in sync with design/stitch/*/code.html so screens render identically.
const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#002022",
        "on-primary": "#003915",
        "on-secondary": "#00363a",
        "on-tertiary-fixed": "#2a1700",
        "error-container": "#93000a",
        "outline-variant": "#3d4a3d",
        "on-surface": "#dfe2eb",
        "inverse-on-surface": "#2d3137",
        "secondary-fixed-dim": "#00dbe9",
        "tertiary-fixed": "#ffddb8",
        "inverse-primary": "#006e2f",
        "primary-container": "#22c55e",
        "surface-container-high": "#262a31",
        "primary-fixed-dim": "#4ae176",
        "surface-container-low": "#181c22",
        primary: "#4be277",
        "on-background": "#dfe2eb",
        "surface-bright": "#353940",
        outline: "#869585",
        "on-primary-fixed-variant": "#005321",
        "on-primary-container": "#004b1e",
        "surface-container-lowest": "#0a0e14",
        "on-secondary-fixed-variant": "#004f54",
        "on-primary-fixed": "#002109",
        "on-tertiary": "#472a00",
        "surface-dim": "#10141a",
        "on-error": "#690005",
        "surface-container-highest": "#31353c",
        "surface-variant": "#31353c",
        surface: "#10141a",
        background: "#10141a",
        "on-tertiary-container": "#5c3800",
        "on-surface-variant": "#bccbb9",
        secondary: "#d3fbff",
        "on-secondary-container": "#00686f",
        "primary-fixed": "#6bff8f",
        error: "#ffb4ab",
        "on-tertiary-fixed-variant": "#653e00",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#ef9900",
        "surface-tint": "#4ae176",
        "tertiary-fixed-dim": "#ffb95f",
        "secondary-fixed": "#7df4ff",
        "inverse-surface": "#dfe2eb",
        tertiary: "#ffba61",
        "secondary-container": "#00eefc",
        "surface-container": "#1c2026",
      },
      borderRadius: { DEFAULT: "0.125rem", lg: "0.25rem", xl: "0.5rem", full: "0.75rem" },
      spacing: {
        "margin-mobile": "1rem",
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        margin: "2.5rem",
        gutter: "1.5rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "gutter-mobile": "0.75rem",
        "space-xl": "2.5rem",
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "display-hero": ["Space Grotesk"],
        "body-sm": ["Inter"],
        "headline-lg": ["Space Grotesk"],
        "body-md": ["Inter"],
        "headline-md": ["Space Grotesk"],
        "label-caps": ["Space Grotesk"],
        "metric-large": ["Space Grotesk"],
        "headline-xl-mobile": ["Space Grotesk"],
        "headline-xl": ["Space Grotesk"],
        "label-badge": ["Inter"],
        "metric-huge": ["Space Grotesk"],
        "display-hero-mobile": ["Space Grotesk"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "700" }],
        "metric-large": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-badge": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "metric-huge": ["48px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
