services:
  postgres:
    image: postgres:17
    container_name: shadowathlete-db

    environment:
      POSTGRES_USER: shadowathlete
      POSTGRES_PASSWORD: shadowathlete
      POSTGRES_DB: shadowathlete

    ports:
      - "5432:5432"

    volumes:
      - shadowathlete_postgres_data:/var/lib/postgresql/data

volumes:
  shadowathlete_postgres_data: