"use client";

// Training plans, generated by the backend planners from the athlete's latest analyzed
// session in each sport.

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import BottomNav from "@/components/BottomNav";
import DrillAvatar from "@/components/DrillAvatar";
import WorkoutPlayer from "@/components/WorkoutPlayer";
import type { BasketballResult } from "@/lib/analysis";
import { api } from "@/lib/api";
import { type Sport, sportFromQuery } from "@/lib/clip";
import { type Recap, type Session, SPORT_BY_ID, SPORT_ICON, SPORT_NAME, relativeDay } from "@/lib/data";
import {
  PLANNED_SPORTS,
  type Plan,
  type StatusResult,
  type Workout,
  type XpEvent,
  type XpState,
  describeMetric,
  generatePlan,
  loadPlans,
  loadXp,
  loadXpHistory,
  setWorkoutStatus,
  trainingStreak,
  workoutMinutes,
  workoutXp,
  workoutsCompleted,
} from "@/lib/training";
import { refreshCurrentUser, useCurrentUser } from "@/lib/useAthlete";

const SPORTS: Sport[] = ["tennis", "cricket", "basketball", "running"];
const ANALYZED = new Set(["completed", "analyzed"]);

const SEVERITY: Record<string, string> = {
  high: "bg-tertiary/15 text-tertiary",
  medium: "bg-secondary-container/15 text-secondary-container",
  low: "bg-primary/15 text-primary",
};

function SeverityChip({ level }: { level: string | null }) {
  if (!level) return null;
  return <span className={`px-2 py-0.5 rounded-full font-label-caps text-[10px] uppercase ${SEVERITY[level] ?? "bg-surface-container-highest text-on-surface-variant"}`}>{level} priority</span>;
}

function StatsHeader({ xp, events, minutes }: { xp: XpState | null; events: XpEvent[] | null; minutes: number }) {
  const level = xp?.level ?? 1;
  const inLevel = xp ? xp.xp - (level - 1) * 1000 : 0;
  const streak = events ? trainingStreak(events) : 0;
  const tiles: [string, string, string][] = [
    ["local_fire_department", events ? String(streak) : "—", streak === 1 ? "day streak" : "days streak"],
    ["fitness_center", events ? String(workoutsCompleted(events)) : "—", "workouts"],
    ["timer", String(minutes), "min trained"],
  ];
  return (
    <section className="rounded-xl bg-surface-container p-space-md flex flex-col gap-space-sm">
      <div className="flex items-center gap-space-sm">
        <div className="w-12 h-12 rounded-xl bg-primary/15 text-primary flex flex-col items-center justify-center shrink-0">
          <span className="font-label-caps text-[9px] uppercase leading-none">Lvl</span>
          <span className="font-headline-md text-body-lg font-bold leading-none tabular-nums">{xp ? level : "—"}</span>
        </div>
        <div className="flex-1 flex flex-col gap-1.5 min-w-0">
          <div className="flex justify-between items-baseline">
            <span className="font-headline-md text-body-md text-on-surface">{xp ? `${xp.xp.toLocaleString()} XP` : "—"}</span>
            <span className="font-body-sm text-[12px] text-on-surface-variant tabular-nums">{xp ? `${xp.xp_remaining} to level ${level + 1}` : ""}</span>
          </div>
          <div className="h-2 rounded-full bg-surface-container-lowest overflow-hidden">
            <div className="h-full rounded-full bg-primary transition-all duration-700" style={{ width: `${Math.min(100, inLevel / 10)}%` }}></div>
          </div>
        </div>
      </div>
      <div className="grid grid-cols-3 gap-2">
        {tiles.map(([icon, value, label]) => (
          <div key={label} className="rounded-lg bg-surface-container-low px-2 py-2 flex items-center gap-1.5">
            <span className={`material-symbols-outlined text-[20px] ${icon === "local_fire_department" && value !== "0" && value !== "—" ? "text-secondary-container" : "text-on-surface-variant"}`}>{icon}</span>
            <div className="flex flex-col min-w-0">
              <span className="font-headline-md text-body-md text-on-surface leading-tight tabular-nums">{value}</span>
              <span className="font-body-sm text-[10px] text-on-surface-variant leading-tight truncate">{label}</span>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}

function WeekStrip({ workouts, onPick }: { workouts: Workout[]; onPick: (w: Workout) => void }) {
  const nextId = workouts.find((w) => w.status === "planned")?.id;
  return (
    <div className="flex items-center gap-1">
      {workouts.map((w, k) => {
        const done = w.status === "completed";
        const skipped = w.status === "skipped";
        const next = w.id === nextId;
        return (
          <div key={w.id} className="contents">
            {k > 0 && <div className={`flex-1 h-0.5 rounded-full ${done ? "bg-primary" : "bg-surface-container-highest"}`}></div>}
            <button
              type="button"
              onClick={() => onPick(w)}
              aria-label={`Session ${w.day}: ${w.title}, ${w.status}`}
              className={`w-9 h-9 rounded-full flex items-center justify-center shrink-0 font-headline-md text-body-sm transition-colors ${
                done ? "bg-primary text-on-primary" : skipped ? "bg-surface-container-highest text-outline" : next ? "bg-surface-container-high text-primary ring-2 ring-primary" : "bg-surface-container-high text-on-surface-variant"
              }`}
            >
              {done ? <span className="material-symbols-outlined text-[18px]">check</span> : skipped ? <span className="material-symbols-outlined text-[18px]">remove</span> : w.day}
            </button>
          </div>
        );
      })}
    </div>
  );
}

function UpNext({ w, onStart, onSkip }: { w: Workout; onStart: () => void; onSkip: () => void }) {
  const first = w.drills?.[0];
  return (
    <section className="rounded-xl bg-surface-container overflow-hidden shadow-[0_0_24px_-8px_rgba(34,197,94,0.35)]">
      <div className="flex gap-space-sm p-space-md pb-0">
        <div className="flex-1 flex flex-col gap-1 min-w-0">
          <span className="font-label-caps text-label-caps text-primary uppercase tracking-widest">Up next · Session {w.day}</span>
          <span className="font-headline-md text-body-lg text-on-surface leading-tight">{w.title}</span>
          {w.source_metric && <span className="font-body-sm text-[12px] text-on-surface-variant">Fixes {describeMetric(w.source_metric, w.current_value).toLowerCase()}</span>}
          <div className="flex flex-wrap gap-1.5 pt-1">
            <span className="px-2 py-0.5 rounded-full bg-surface-container-high font-label-caps text-[10px] uppercase text-on-surface-variant">{workoutMinutes(w)} min</span>
            <span className="px-2 py-0.5 rounded-full bg-surface-container-high font-label-caps text-[10px] uppercase text-on-surface-variant">{(w.drills ?? []).length} drills</span>
            <span className="px-2 py-0.5 rounded-full bg-primary/15 font-label-caps text-[10px] uppercase text-primary">+{workoutXp(w)} XP</span>
          </div>
        </div>
        {first && <DrillAvatar drill={`${first.id} ${first.name}`} size={104} className="shrink-0 -mr-1 -mt-1" />}
      </div>
      <div className="grid grid-cols-[1fr_auto] gap-2 p-space-md">
        <button type="button" onClick={onStart} className="py-3 rounded-xl bg-primary text-on-primary font-headline-md text-body-md font-bold flex items-center justify-center gap-1.5">
          <span className="material-symbols-outlined text-[20px]">play_arrow</span>
          Start session
        </button>
        <button type="button" onClick={onSkip} className="px-space-md py-3 rounded-xl bg-surface-container-high text-on-surface-variant font-headline-md text-body-sm">
          Skip
        </button>
      </div>
    </section>
  );
}

function WorkoutCard({ w, open, onToggle, onStart, onSkip }: { w: Workout; open: boolean; onToggle: () => void; onStart: () => void; onSkip: () => void }) {
  const done = w.status === "completed";
  const skipped = w.status === "skipped";
  return (
    <div className={`rounded-xl bg-surface-container overflow-hidden ${done ? "opacity-80" : ""}`}>
      <button type="button" onClick={onToggle} className="w-full flex items-center gap-space-sm p-space-md text-left">
        <div className={`w-10 h-10 rounded-lg flex items-center justify-center shrink-0 font-headline-md text-body-md ${done ? "bg-primary text-on-primary" : skipped ? "bg-surface-container-highest text-outline" : "bg-surface-container-high text-on-surface"}`}>
          {done ? <span className="material-symbols-outlined text-[20px]">check</span> : w.day}
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2">
            <span className={`font-body-md text-body-md font-semibold truncate ${skipped ? "text-outline line-through" : "text-on-surface"}`}>{w.title}</span>
          </div>
          <span className="font-body-sm text-[12px] text-on-surface-variant">
            {workoutMinutes(w)} min · {done ? "done" : skipped ? "skipped" : `+${workoutXp(w)} XP`}
          </span>
        </div>
        <span className="material-symbols-outlined text-on-surface-variant">{open ? "expand_less" : "expand_more"}</span>
      </button>

      {open && (
        <div className="px-space-md pb-space-md flex flex-col gap-space-sm">
          {w.warmup && (
            <div className="flex flex-col gap-1">
              <span className="font-label-caps text-label-caps uppercase text-on-surface-variant">Warm-up · {w.warmup.duration_minutes} min</span>
              <span className="font-body-sm text-body-sm text-on-surface">{w.warmup.activities.join(" · ")}</span>
            </div>
          )}
          {(w.drills ?? []).map((d) => (
            <div key={d.id} className="rounded-lg bg-surface-container-low p-space-sm flex gap-space-sm">
              <DrillAvatar drill={`${d.id} ${d.name}`} size={64} className="shrink-0 rounded-lg bg-surface-container" />
              <div className="flex flex-col gap-0.5 min-w-0">
                <span className="font-body-md text-body-md font-semibold text-on-surface leading-tight">{d.name}</span>
                <span className="font-label-caps text-[11px] uppercase text-primary">
                  {[d.sets && d.reps ? `${d.sets} × ${d.reps}` : d.sets ? `${d.sets} sets` : "", d.duration_minutes ? `${d.duration_minutes} min` : ""].filter(Boolean).join(" · ")}
                </span>
                {d.description && <span className="font-body-sm text-[13px] text-on-surface-variant leading-snug">{d.description}</span>}
              </div>
            </div>
          ))}
          {w.cooldown && (
            <div className="flex flex-col gap-1">
              <span className="font-label-caps text-label-caps uppercase text-on-surface-variant">Cool-down · {w.cooldown.duration_minutes} min</span>
              <span className="font-body-sm text-body-sm text-on-surface">{w.cooldown.activities.join(" · ")}</span>
            </div>
          )}
          {w.status === "planned" && (
            <div className="grid grid-cols-2 gap-2 pt-1">
              <button type="button" onClick={onStart} className="py-2.5 rounded-xl bg-primary text-on-primary font-headline-md text-body-sm font-bold flex items-center justify-center gap-1.5">
                <span className="material-symbols-outlined text-[18px]">play_arrow</span>
                Start
              </button>
              <button type="button" onClick={onSkip} className="py-2.5 rounded-xl bg-surface-container-high text-on-surface-variant font-headline-md text-body-sm flex items-center justify-center gap-1.5">
                <span className="material-symbols-outlined text-[18px]">skip_next</span>
                Skip
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export default function Train() {
  const router = useRouter();
  const user = useCurrentUser();
  const athleteId = user.status === "signed-in" ? user.profile?.id : undefined;
  const [sport, setSport] = useState<Sport>("tennis");
  const [plans, setPlans] = useState<Plan[] | null>(null);
  const [sessions, setSessions] = useState<Session[] | null>(null);
  const [bball, setBball] = useState<BasketballResult | null>(null);
  const [open, setOpen] = useState<number | null>(null);
  const [busy, setBusy] = useState(false);
  const [xp, setXp] = useState<XpState | null>(null);
  const [events, setEvents] = useState<XpEvent[] | null>(null);
  const [playing, setPlaying] = useState<Workout | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => setSport(sportFromQuery()), []);

  const refresh = useCallback(async () => {
    if (!athleteId) return;
    const [p, s, x, h] = await Promise.all([
      loadPlans(athleteId).catch(() => [] as Plan[]),
      api<Session[]>("/sessions").catch(() => [] as Session[]),
      loadXp().catch(() => null),
      loadXpHistory().catch(() => null),
    ]);
    setPlans(p);
    setSessions(s);
    setXp(x);
    setEvents(h);
  }, [athleteId]);

  useEffect(() => {
    refresh();
  }, [refresh]);

  const latest = (sessions ?? [])
    .filter((s) => SPORT_BY_ID[s.sport_id] === sport && ANALYZED.has(s.status))
    .sort((a, b) => b.created_at.localeCompare(a.created_at))[0];
  const plan = (plans ?? []).find((p) => p.sport === sport);
  const done = plan?.workouts.filter((w) => w.status === "completed").length ?? 0;
  const total = plan?.workouts.length ?? 0;
  const focus = plan ? [...new Map(plan.workouts.map((w) => [w.title, w])).values()] : [];
  const upNext = plan?.workouts.find((w) => w.status === "planned");
  const minutesTrained = (plans ?? []).flatMap((p) => p.workouts).filter((w) => w.status === "completed").reduce((a, w) => a + workoutMinutes(w), 0);

  // Basketball: the pipeline's coach feedback, shown before a plan has been built.
  useEffect(() => {
    setBball(null);
    if (sport !== "basketball" || !latest) return;
    api<Recap>(`/sessions/${latest.id}/recap`).then((r) => setBball((r.analysis?.analysis_data ?? null) as BasketballResult | null), () => {});
  }, [sport, latest?.id]); // eslint-disable-line react-hooks/exhaustive-deps

  function choose(s: Sport) {
    setSport(s);
    setOpen(null);
    setError(null);
    router.replace(`/train?sport=${s}`);
  }

  async function create() {
    if (!latest) return;
    setBusy(true);
    setError(null);
    try {
      const res = await generatePlan(sport, latest.id);
      if (res.status === "maintenance") setError(res.message ?? "No major weaknesses found — keep training as usual.");
      await refresh();
    } catch (e) {
      setError(e instanceof Error ? e.message : "Couldn't create a plan");
    } finally {
      setBusy(false);
    }
  }

  function markLocal(id: number, status: Workout["status"]) {
    setPlans((ps) => ps?.map((p) => ({ ...p, workouts: p.workouts.map((x) => (x.id === id ? { ...x, status } : x)) })) ?? null);
  }

  async function skip(w: Workout) {
    markLocal(w.id, "skipped");
    await setWorkoutStatus(w.id, "skip").catch(() => refresh());
  }

  function completed(w: Workout, r: StatusResult) {
    markLocal(w.id, "completed");
    if (r.xp != null && r.level != null) setXp({ xp: r.xp, level: r.level, xp_for_next_level: r.level * 1000, xp_remaining: r.level * 1000 - r.xp });
    loadXpHistory().then(setEvents, () => {});
    refreshCurrentUser().catch(() => {});
  }

  return (
    <div className="bg-surface text-on-surface font-body-md text-body-md min-h-screen flex flex-col antialiased">
      <header className="fixed top-0 inset-x-0 z-50 bg-surface/85 backdrop-blur-xl pt-safe">
        <div className="h-16 px-margin-mobile flex items-center">
          <h1 className="font-headline-md text-headline-md text-on-surface">Training</h1>
        </div>
      </header>

      <main className="flex flex-col w-full pt-20 pb-28 px-margin-mobile gap-space-md">
        <div className="grid grid-cols-4 gap-2">
          {SPORTS.map((s) => (
            <button key={s} type="button" onClick={() => choose(s)} aria-pressed={s === sport} className={`flex flex-col items-center gap-1 py-2 rounded-xl transition-colors ${s === sport ? "bg-surface-container-highest text-primary" : "bg-surface-container text-on-surface-variant"}`}>
              <span className="material-symbols-outlined text-[22px]">{SPORT_ICON[s]}</span>
              <span className="font-label-caps text-[10px] uppercase">{SPORT_NAME[s]}</span>
            </button>
          ))}
        </div>

        {athleteId && <StatsHeader xp={xp} events={events} minutes={minutesTrained} />}

        {user.status !== "signed-in" && user.status !== "loading" && <p className="font-body-sm text-body-sm text-on-surface-variant">Sign in to get a training plan.</p>}
        {error && <p className="font-body-sm text-body-sm text-tertiary">{error}</p>}
        {athleteId && !plans && (
          <div className="flex flex-col gap-space-md animate-pulse">
            <div className="h-36 rounded-xl bg-surface-container"></div>
            <div className="h-16 rounded-xl bg-surface-container"></div>
            <div className="h-16 rounded-xl bg-surface-container"></div>
          </div>
        )}

        {plans && sport === "basketball" && !plan && bball?.training && (
          <section className="rounded-xl bg-surface-container p-space-md flex flex-col gap-space-sm">
            <span className="font-label-caps text-label-caps text-primary uppercase tracking-widest">From your last session</span>
            <span className="font-headline-md text-body-lg text-on-surface">Technique score {bball.training.technique_score ?? "—"}</span>
            {(bball.training.feedback ?? []).map((f) => (
              <span key={f} className="flex items-start gap-2 font-body-sm text-body-sm text-on-surface-variant">
                <span className="material-symbols-outlined text-[18px] text-secondary-container">insights</span>
                {f}
              </span>
            ))}
          </section>
        )}

        {plans && PLANNED_SPORTS.includes(sport) && (
          plan ? (
            <>
              {upNext ? (
                <UpNext w={upNext} onStart={() => setPlaying(upNext)} onSkip={() => skip(upNext)} />
              ) : (
                <section className="rounded-xl bg-surface-container p-space-md flex items-center gap-space-sm shadow-[0_0_24px_-8px_rgba(34,197,94,0.35)]">
                  <DrillAvatar drill="squat jump" size={72} className="shrink-0" />
                  <div className="flex flex-col">
                    <span className="font-label-caps text-label-caps text-primary uppercase tracking-widest">Week complete</span>
                    <span className="font-body-sm text-body-sm text-on-surface-variant">Record a new session to see what changed, then update your plan.</span>
                  </div>
                </section>
              )}

              <section className="rounded-xl bg-surface-container p-space-md flex flex-col gap-space-sm">
                <div className="flex items-center justify-between">
                  <span className="font-headline-md text-body-md text-on-surface">This week</span>
                  <span className="font-body-sm text-[12px] text-on-surface-variant tabular-nums">
                    {done}/{total} done · {plan.workouts.filter((w) => w.status === "completed").reduce((a, w) => a + workoutMinutes(w), 0)}/{plan.workouts.reduce((a, w) => a + workoutMinutes(w), 0)} min
                  </span>
                </div>
                <WeekStrip workouts={plan.workouts} onPick={(w) => setOpen(w.id)} />
                <details className="group pt-1">
                  <summary className="list-none flex items-center justify-between cursor-pointer font-label-caps text-label-caps uppercase text-on-surface-variant">
                    Why these focus areas
                    <span className="material-symbols-outlined text-[18px] transition-transform group-open:rotate-180">expand_more</span>
                  </summary>
                  <div className="flex flex-col gap-2 pt-2">
                    {focus.map((w) => (
                      <div key={w.title} className="flex items-center justify-between gap-2">
                        <div className="flex flex-col min-w-0">
                          <span className="font-body-sm text-body-sm text-on-surface">{w.title}</span>
                          <span className="font-body-sm text-[12px] text-outline truncate">{describeMetric(w.source_metric, w.current_value)}</span>
                        </div>
                        <SeverityChip level={w.severity} />
                      </div>
                    ))}
                  </div>
                </details>
              </section>

              <div className="flex flex-col gap-2">
                {plan.workouts.map((w) => (
                  <WorkoutCard key={w.id} w={w} open={open === w.id} onToggle={() => setOpen(open === w.id ? null : w.id)} onStart={() => setPlaying(w)} onSkip={() => skip(w)} />
                ))}
              </div>

              {latest && (
                <button type="button" onClick={create} disabled={busy} className="py-3 rounded-xl bg-surface-container-high text-on-surface font-headline-md text-body-sm flex items-center justify-center gap-1.5 disabled:opacity-70">
                  <span className={`material-symbols-outlined text-[18px] ${busy ? "animate-spin" : ""}`}>{busy ? "progress_activity" : "refresh"}</span>
                  Update from latest session ({relativeDay(latest.created_at).toLowerCase()})
                </button>
              )}
            </>
          ) : latest ? (
            <section className="rounded-xl bg-surface-container p-space-lg flex flex-col items-center text-center gap-space-sm">
              <span className="material-symbols-outlined text-[36px] text-primary">fitness_center</span>
              <span className="font-headline-md text-body-lg text-on-surface">Build your {SPORT_NAME[sport].toLowerCase()} plan</span>
              <span className="font-body-sm text-body-sm text-on-surface-variant">A 4-session week targeting the weaknesses found in your latest analyzed session (#{latest.id}).</span>
              <button type="button" onClick={create} disabled={busy} className="mt-1 px-space-lg py-3 rounded-xl bg-primary text-on-primary font-headline-md text-body-md font-bold flex items-center gap-2 disabled:opacity-70">
                <span className={`material-symbols-outlined text-[20px] ${busy ? "animate-spin" : ""}`}>{busy ? "progress_activity" : "auto_awesome"}</span>
                {busy ? "Building…" : "Create my plan"}
              </button>
            </section>
          ) : (
            <section className="rounded-xl bg-surface-container p-space-lg flex flex-col items-center text-center gap-space-sm">
              <span className="material-symbols-outlined text-[36px] text-outline">{SPORT_ICON[sport]}</span>
              <span className="font-body-md text-body-md text-on-surface-variant">Analyze a {SPORT_NAME[sport].toLowerCase()} session and your plan will be built from it.</span>
              <Link href={`/capture/upload?sport=${sport}`} className="px-space-md py-2.5 rounded-xl bg-primary text-on-primary font-headline-md text-body-sm font-bold">Record a session</Link>
            </section>
          )
        )}
      </main>
      <BottomNav />
      {playing && <WorkoutPlayer workout={playing} onClose={() => setPlaying(null)} onCompleted={(r) => completed(playing, r)} />}
    </div>
  );
}
