"""add shadow tests

Revision ID: 393ae23a8269
Revises: e2b8561be651
Create Date: 2026-10-04 11:38:46.053378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '393ae23a8269'
down_revision: Union[str, None] = 'e2b8561be651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shadow_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('baseline_session_id', sa.Integer(), nullable=True),
    sa.Column('resolved_session_id', sa.Integer(), nullable=True),
    sa.Column('predictions', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shadow_tests_athlete_id'), 'shadow_tests', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_shadow_tests_id'), 'shadow_tests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shadow_tests_id'), table_name='shadow_tests')
    op.drop_index(op.f('ix_shadow_tests_athlete_id'), table_name='shadow_tests')
    op.drop_table('shadow_tests')
    # ### end Alembic commands ###
