"""add sport metrics and athlete attributes

Revision ID: 43e10c87e0c8
Revises: e314080a0382
Create Date: 2026-10-03 16:10:51.715306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e10c87e0c8'
down_revision: Union[str, None] = 'e314080a0382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('attribute_type', sa.String(length=50), nullable=False),
    sa.Column('current_score', sa.Float(), nullable=False),
    sa.Column('peak_score', sa.Float(), nullable=False),
    sa.Column('target_score', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'attribute_type', name='uq_athlete_attribute')
    )
    op.create_index(op.f('ix_athlete_attributes_athlete_id'), 'athlete_attributes', ['athlete_id'], unique=False)
    op.create_table('sport_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['video_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sport_metrics_id'), 'sport_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_sport_metrics_session_id'), 'sport_metrics', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sport_metrics_session_id'), table_name='sport_metrics')
    op.drop_index(op.f('ix_sport_metrics_id'), table_name='sport_metrics')
    op.drop_table('sport_metrics')
    op.drop_index(op.f('ix_athlete_attributes_athlete_id'), table_name='athlete_attributes')
    op.drop_table('athlete_attributes')
    # ### end Alembic commands ###
