"""add recovery training shadow records achievements

Revision ID: cd599400a47e
Revises: edd85b0948ad
Create Date: 2026-10-03 16:31:19.824792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd599400a47e'
down_revision: Union[str, None] = 'edd85b0948ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    op.create_table('athlete_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_achievements_athlete_id'), 'athlete_achievements', ['athlete_id'], unique=False)
    op.create_table('personal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('achieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_records_athlete_id'), 'personal_records', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_personal_records_id'), 'personal_records', ['id'], unique=False)
    op.create_table('recovery_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('sleep_duration', sa.Float(), nullable=True),
    sa.Column('sleep_quality', sa.Float(), nullable=True),
    sa.Column('resting_hr', sa.Float(), nullable=True),
    sa.Column('hrv', sa.Float(), nullable=True),
    sa.Column('fatigue', sa.Float(), nullable=True),
    sa.Column('recovery_score', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_metrics_athlete_id'), 'recovery_metrics', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_recovery_metrics_id'), 'recovery_metrics', ['id'], unique=False)
    op.create_table('shadow_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('shadow_value', sa.Float(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shadow_challenges_athlete_id'), 'shadow_challenges', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_shadow_challenges_id'), 'shadow_challenges', ['id'], unique=False)
    op.create_table('training_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('focus', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_plans_athlete_id'), 'training_plans', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_training_plans_id'), 'training_plans', ['id'], unique=False)
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_plan_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('intensity', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['training_plan_id'], ['training_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workouts_id'), 'workouts', ['id'], unique=False)
    op.create_index(op.f('ix_workouts_training_plan_id'), 'workouts', ['training_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workouts_training_plan_id'), table_name='workouts')
    op.drop_index(op.f('ix_workouts_id'), table_name='workouts')
    op.drop_table('workouts')
    op.drop_index(op.f('ix_training_plans_id'), table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_athlete_id'), table_name='training_plans')
    op.drop_table('training_plans')
    op.drop_index(op.f('ix_shadow_challenges_id'), table_name='shadow_challenges')
    op.drop_index(op.f('ix_shadow_challenges_athlete_id'), table_name='shadow_challenges')
    op.drop_table('shadow_challenges')
    op.drop_index(op.f('ix_recovery_metrics_id'), table_name='recovery_metrics')
    op.drop_index(op.f('ix_recovery_metrics_athlete_id'), table_name='recovery_metrics')
    op.drop_table('recovery_metrics')
    op.drop_index(op.f('ix_personal_records_id'), table_name='personal_records')
    op.drop_index(op.f('ix_personal_records_athlete_id'), table_name='personal_records')
    op.drop_table('personal_records')
    op.drop_index(op.f('ix_athlete_achievements_athlete_id'), table_name='athlete_achievements')
    op.drop_table('athlete_achievements')
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
