"""add coach challenges technique replay references

Revision ID: dfcd43363993
Revises: cd599400a47e
Create Date: 2026-10-03 16:58:27.691203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfcd43363993'
down_revision: Union[str, None] = 'cd599400a47e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport_reference_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=100), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sport_reference_ranges_sport_id'), 'sport_reference_ranges', ['sport_id'], unique=False)
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_athlete_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_id'), 'challenges', ['id'], unique=False)
    op.create_table('coach_athlete_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_user_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coach_user_id', 'athlete_id', name='uq_coach_athlete')
    )
    op.create_index(op.f('ix_coach_athlete_relationships_athlete_id'), 'coach_athlete_relationships', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_coach_athlete_relationships_coach_user_id'), 'coach_athlete_relationships', ['coach_user_id'], unique=False)
    op.create_table('coach_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_messages_athlete_id'), 'coach_messages', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_coach_messages_id'), 'coach_messages', ['id'], unique=False)
    op.create_table('coach_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_recommendations_athlete_id'), 'coach_recommendations', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_coach_recommendations_id'), 'coach_recommendations', ['id'], unique=False)
    op.create_table('movement_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=False),
    sa.Column('tolerance', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movement_baselines_athlete_id'), 'movement_baselines', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_movement_baselines_id'), 'movement_baselines', ['id'], unique=False)
    op.create_table('risk_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_signals_athlete_id'), 'risk_signals', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_risk_signals_id'), 'risk_signals', ['id'], unique=False)
    op.create_table('sport_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('source_attribute', sa.String(length=100), nullable=False),
    sa.Column('source_change', sa.Float(), nullable=False),
    sa.Column('target_sport_id', sa.Integer(), nullable=False),
    sa.Column('target_metric', sa.String(length=100), nullable=False),
    sa.Column('projected_change', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_sport_id'], ['sports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sport_transfers_athlete_id'), 'sport_transfers', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_sport_transfers_id'), 'sport_transfers', ['id'], unique=False)
    op.create_table('xp_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xp_events_athlete_id'), 'xp_events', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_xp_events_id'), 'xp_events', ['id'], unique=False)
    op.create_table('challenge_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('progress_value', sa.Float(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'athlete_id', name='uq_challenge_participant')
    )
    op.create_table('performance_explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['video_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_explanations_id'), 'performance_explanations', ['id'], unique=False)
    op.create_index(op.f('ix_performance_explanations_session_id'), 'performance_explanations', ['session_id'], unique=False)
    op.create_table('performance_highlights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('highlight_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['video_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_highlights_athlete_id'), 'performance_highlights', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_performance_highlights_id'), 'performance_highlights', ['id'], unique=False)
    op.create_table('session_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('strongest_metric', sa.String(length=100), nullable=True),
    sa.Column('weakest_metric', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['video_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_analyses_id'), 'session_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_session_analyses_session_id'), 'session_analyses', ['session_id'], unique=True)
    op.create_table('technique_replays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('issue', sa.Text(), nullable=False),
    sa.Column('body_part', sa.String(length=100), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('suggested_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['video_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technique_replays_session_id'), 'technique_replays', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technique_replays_session_id'), table_name='technique_replays')
    op.drop_table('technique_replays')
    op.drop_index(op.f('ix_session_analyses_session_id'), table_name='session_analyses')
    op.drop_index(op.f('ix_session_analyses_id'), table_name='session_analyses')
    op.drop_table('session_analyses')
    op.drop_index(op.f('ix_performance_highlights_id'), table_name='performance_highlights')
    op.drop_index(op.f('ix_performance_highlights_athlete_id'), table_name='performance_highlights')
    op.drop_table('performance_highlights')
    op.drop_index(op.f('ix_performance_explanations_session_id'), table_name='performance_explanations')
    op.drop_index(op.f('ix_performance_explanations_id'), table_name='performance_explanations')
    op.drop_table('performance_explanations')
    op.drop_table('challenge_participants')
    op.drop_index(op.f('ix_xp_events_id'), table_name='xp_events')
    op.drop_index(op.f('ix_xp_events_athlete_id'), table_name='xp_events')
    op.drop_table('xp_events')
    op.drop_index(op.f('ix_sport_transfers_id'), table_name='sport_transfers')
    op.drop_index(op.f('ix_sport_transfers_athlete_id'), table_name='sport_transfers')
    op.drop_table('sport_transfers')
    op.drop_index(op.f('ix_risk_signals_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_athlete_id'), table_name='risk_signals')
    op.drop_table('risk_signals')
    op.drop_index(op.f('ix_movement_baselines_id'), table_name='movement_baselines')
    op.drop_index(op.f('ix_movement_baselines_athlete_id'), table_name='movement_baselines')
    op.drop_table('movement_baselines')
    op.drop_index(op.f('ix_coach_recommendations_id'), table_name='coach_recommendations')
    op.drop_index(op.f('ix_coach_recommendations_athlete_id'), table_name='coach_recommendations')
    op.drop_table('coach_recommendations')
    op.drop_index(op.f('ix_coach_messages_id'), table_name='coach_messages')
    op.drop_index(op.f('ix_coach_messages_athlete_id'), table_name='coach_messages')
    op.drop_table('coach_messages')
    op.drop_index(op.f('ix_coach_athlete_relationships_coach_user_id'), table_name='coach_athlete_relationships')
    op.drop_index(op.f('ix_coach_athlete_relationships_athlete_id'), table_name='coach_athlete_relationships')
    op.drop_table('coach_athlete_relationships')
    op.drop_index(op.f('ix_challenges_id'), table_name='challenges')
    op.drop_table('challenges')
    op.drop_index(op.f('ix_sport_reference_ranges_sport_id'), table_name='sport_reference_ranges')
    op.drop_table('sport_reference_ranges')
    # ### end Alembic commands ###
