"""add generated workout fields

Revision ID: e2b8561be651
Revises: 72567def1326
Create Date: 2026-10-04 03:44:10.947546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2b8561be651'
down_revision: Union[str, None] = '72567def1326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('priority_score', sa.Float(), nullable=True))
    op.add_column('workouts', sa.Column('source_metric', sa.String(length=100), nullable=True))
    op.add_column('workouts', sa.Column('current_value', sa.JSON(), nullable=True))
    op.add_column('workouts', sa.Column('severity', sa.String(length=50), nullable=True))
    op.add_column('workouts', sa.Column('warmup', sa.JSON(), nullable=True))
    op.add_column('workouts', sa.Column('drills', sa.JSON(), nullable=True))
    op.add_column('workouts', sa.Column('cooldown', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'cooldown')
    op.drop_column('workouts', 'drills')
    op.drop_column('workouts', 'warmup')
    op.drop_column('workouts', 'severity')
    op.drop_column('workouts', 'current_value')
    op.drop_column('workouts', 'source_metric')
    op.drop_column('workouts', 'priority_score')
    # ### end Alembic commands ###
