"""add athlete sports and sessions

Revision ID: e314080a0382
Revises: b756e5a78372
Create Date: 2026-10-03 15:56:21.212464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e314080a0382'
down_revision: Union[str, None] = 'b756e5a78372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_sports_id'), 'sports', ['id'], unique=False)
    op.create_index(op.f('ix_sports_slug'), 'sports', ['slug'], unique=True)
    op.create_table('athlete_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('athlete_score', sa.Float(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_profiles_id'), 'athlete_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_athlete_profiles_user_id'), 'athlete_profiles', ['user_id'], unique=True)
    op.create_table('athlete_sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'sport_id', name='uq_athlete_sport')
    )
    op.create_index(op.f('ix_athlete_sports_athlete_id'), 'athlete_sports', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_athlete_sports_sport_id'), 'athlete_sports', ['sport_id'], unique=False)
    op.create_table('video_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_sessions_athlete_id'), 'video_sessions', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_video_sessions_id'), 'video_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_video_sessions_sport_id'), 'video_sessions', ['sport_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_sessions_sport_id'), table_name='video_sessions')
    op.drop_index(op.f('ix_video_sessions_id'), table_name='video_sessions')
    op.drop_index(op.f('ix_video_sessions_athlete_id'), table_name='video_sessions')
    op.drop_table('video_sessions')
    op.drop_index(op.f('ix_athlete_sports_sport_id'), table_name='athlete_sports')
    op.drop_index(op.f('ix_athlete_sports_athlete_id'), table_name='athlete_sports')
    op.drop_table('athlete_sports')
    op.drop_index(op.f('ix_athlete_profiles_user_id'), table_name='athlete_profiles')
    op.drop_index(op.f('ix_athlete_profiles_id'), table_name='athlete_profiles')
    op.drop_table('athlete_profiles')
    op.drop_index(op.f('ix_sports_slug'), table_name='sports')
    op.drop_index(op.f('ix_sports_id'), table_name='sports')
    op.drop_table('sports')
    # ### end Alembic commands ###
