"""add athlete progress

Revision ID: edd85b0948ad
Revises: 43e10c87e0c8
Create Date: 2026-10-03 16:14:50.129888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd85b0948ad'
down_revision: Union[str, None] = '43e10c87e0c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('athlete_score', sa.Float(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_progress_athlete_id'), 'athlete_progress', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_athlete_progress_id'), 'athlete_progress', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_athlete_progress_id'), table_name='athlete_progress')
    op.drop_index(op.f('ix_athlete_progress_athlete_id'), table_name='athlete_progress')
    op.drop_table('athlete_progress')
    # ### end Alembic commands ###
