"""add analysis data

Revision ID: f15c0ec420f0
Revises: dfcd43363993
Create Date: 2026-10-04 01:47:45.185027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f15c0ec420f0'
down_revision: Union[str, None] = 'dfcd43363993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_analyses', sa.Column('analysis_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_analyses', 'analysis_data')
    # ### end Alembic commands ###
